GET http://localhost:3003
###
GET http://localhost:3003/api/blogs
###
GET http://localhost:3003/api/blogs/2
###
DELETE http://localhost:3003/api/blogs/2
###
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Book Title Java",
    "author": "Author Is second",
    "url": "https://google.fi",
    "likes": 483
}
###