GET http://localhost:3003
###
GET http://localhost:3003/api/blogs
###
GET http://localhost:3003/api/blogs/2
###
DELETE http://localhost:3003/api/blogs/65cf2a4852342fb382fd3c17
###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "4533Book Title Java",
    "author": "33Author Is second",
    "url": "33https://google.fi",
    "likes": 48366456456
}
###
PUT http://localhost:3003/api/blogs/65cf263c2e513f8b9e034125 HTTP/1.1
content-type: application/json

{
    "title": "8888Book Title Java",
    "author": "3888Autuuhor Is second",
    "url": "88https://uugoogle.fi",
    "likes": 88
}
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "jukka788",
    "name": "Pokka Poika",
    "password": "secret8888"
}
###
GET http://localhost:3003/api/users