version: "3.8"

services:
  app:
    image: blog-app-frontti-dev
    build:
      context: ./blog-app-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-app-frontend:/usr/src/app
    environment:
      - PORT=3003
  
    container_name: frontti-dev

  server:
    image: blog-app-back-dev
    build:
      context: ./blog-app-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./blog-app-backend:/usr/src/app
    env_file:
      - ./blog-app-backend/.env
    container_name: back-dev

volumes:
  mongo_data: